# .readthedocs.yml

version: 2

sphinx:
    builder: html
    configuration: docs/conf.py

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

python:
  install:
    - requirements: docs/requirements.txt
