# .readthedocs.yml

version: 2

sphinx:
    builder: html
    configuration: docs/conf.py

build:
  os: latest
  tools:
    python: "3.12"

python:
  install:
    - requirements: docs/requirements.txt
