name: Documentation 
description: Documentation Issue
title: "[docs]: "
labels: [docs]
assignees:
  - wspear
  - eugeneswalker
  - sameershende
body:
  - type: textarea
    id: Description
    attributes:
      label: Request Description
      placeholder: "Please describe issue with documentation"
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: true
