name: Check URLs

on: [push, pull_request]

jobs:
  urlcheck:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: URLs-checker
      uses: urlstechie/urlchecker-action@0.0.34
      with:

        # clone devel
        branch: main
        # A comma-separated list of file types to cover in the URL checks
        file_types: .md,.rst

        # Choose whether to include file with no URLs in the prints.
        print_all: false

        # timeout in 10 seconds if url is not reached
        timeout: 10

        # How many times to retry a failed request (defaults to 1)
        retry_count: 5
        
        verbose: true
        
        exclude_patterns: https://cache.e4s.io/
        
        exclude_urls: https://img.shields.io/github/v/release/STEllAR-GROUP/hpx/,https://img.shields.io/github/release-date/STEllAR-GROUP/hpx/,https://github.com/E4S-Project/e4s/actions,https://github.com/E4S-Project/e4s/blob/master/LICENSE
